// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWCXCFZtyxd-4Vpdhst62hBn24pY8Z2EQ',
    appId: '1:409846969937:web:7e27b31c99aef8dc92aa70',
    messagingSenderId: '409846969937',
    projectId: 'push-notification-ee0f1',
    authDomain: 'push-notification-ee0f1.firebaseapp.com',
    storageBucket: 'push-notification-ee0f1.appspot.com',
    measurementId: 'G-RMEMC0N7RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc3lMJeTjWPFHl3Dwp8b9jjjxUBq1wyMg',
    appId: '1:409846969937:android:66b14b1b8055eb8092aa70',
    messagingSenderId: '409846969937',
    projectId: 'push-notification-ee0f1',
    storageBucket: 'push-notification-ee0f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-p1FRJNJ3huK1NmAHxn2FbaPUp81zQ0c',
    appId: '1:409846969937:ios:e574565e7392d00592aa70',
    messagingSenderId: '409846969937',
    projectId: 'push-notification-ee0f1',
    storageBucket: 'push-notification-ee0f1.appspot.com',
    iosClientId: '409846969937-jfeb3fvf76o44dl5urs740jrvtqdlt4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-p1FRJNJ3huK1NmAHxn2FbaPUp81zQ0c',
    appId: '1:409846969937:ios:5833c0cf227bf4a192aa70',
    messagingSenderId: '409846969937',
    projectId: 'push-notification-ee0f1',
    storageBucket: 'push-notification-ee0f1.appspot.com',
    iosClientId: '409846969937-nt1mletra3emjqo68uskohv5jkpcq2la.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPushNotification.RunnerTests',
  );
}
